### ISSUE TITLE
Complete T-Regx 0.9.0 features

### ISSUE THREAD

**Issue by danon** [T-Regx/T-Regx.github.io#7]
- optional replaces (`orElse()`, `orReturn()`, `orThrow()`)
 - Mess in `MatchGroup` details
 - `CompositePattern`
 - `replace()->by()->map()` + `orElse`/`orReturn`/`orThrow`
 - Inline groups
 - `fluent()`

**Comment by danon** [comment]
Move "Count occurrances" to "Match" sub-category?

**Comment by danon** [comment]
> Method filter() filters an array and returns values re-indexed to match the removed elements (like array_filter()).

Is not true

**Comment by danon** [comment]
Update Brain Strain

**Comment by danon** [comment]
Using "Explicity rule" link to actual anchor, not a page

**Comment by Danon** [comment]
Add code tabs to every page

**Comment by danon** [comment]
Add features:
 - format
 - template
 - `Detail` instead of `Match`
 - focus (also in groups) and substitute
 - fluent

**Comment by danon** [comment]
Add prepared patttern `Pattern::prepare()` back to docs

**Comment by danon** [comment]
Add streams, `asInt()` and `asArray()`

**Comment by danon** [comment]
`distinct()`

**Comment by danon** [comment]
`nth()`

**Comment by danon** [comment]
``otherwise()`/`throwingOtherwise()`/`returningOtherwise()``

**Comment by danon** [comment]
`groupBy()` and `groupByCallback()`

**Comment by danon** [comment]
`preg::grep_keys()` actually, create a whole list of methods

**Comment by danon** [comment]
`flatMapAssoc()`
